//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Il codice sorgente è stato generato automaticamente da Microsoft.VSDesigner, versione 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace MailTicketAzureMvc.ServizioPrevendita {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServizioPrevenditaSoap", Namespace="http://wsfiscale.mailticket.it/")]
    public partial class ServizioPrevendita : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback VerificaCodicePROperationCompleted;
        
        private System.Threading.SendOrPostCallback AggiungiAlCarrelloOperationCompleted;
        
        private System.Threading.SendOrPostCallback RimuoviDalCarrelloOperationCompleted;
        
        private System.Threading.SendOrPostCallback EliminaCarrelloOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConfermaCarrelloOperationCompleted;
        
        private System.Threading.SendOrPostCallback AggiornaOrdineOperationCompleted;
        
        private System.Threading.SendOrPostCallback RegistraAnagintOperationCompleted;
        
        private System.Threading.SendOrPostCallback RiepilogoOrdineOperationCompleted;
        
        private System.Threading.SendOrPostCallback AvviaPagamentoOrdineOperationCompleted;
        
        private System.Threading.SendOrPostCallback RicalcolaCarrelloOperationCompleted;
        
        private System.Threading.SendOrPostCallback ElencoOrdiniOperationCompleted;
        
        private System.Threading.SendOrPostCallback RecuperaEventiMailticketOperationCompleted;
        
        private System.Threading.SendOrPostCallback RecuperaBigliettiManEinetOperationCompleted;
        
        private System.Threading.SendOrPostCallback RecuperaBigliettiManMinetOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServizioPrevendita() {
            this.Url = global::MailTicketAzureMvc.Properties.Settings.Default.MailTicketAzureMvc_ServizioPrevendita_ServizioPrevendita;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event VerificaCodicePRCompletedEventHandler VerificaCodicePRCompleted;
        
        /// <remarks/>
        public event AggiungiAlCarrelloCompletedEventHandler AggiungiAlCarrelloCompleted;
        
        /// <remarks/>
        public event RimuoviDalCarrelloCompletedEventHandler RimuoviDalCarrelloCompleted;
        
        /// <remarks/>
        public event EliminaCarrelloCompletedEventHandler EliminaCarrelloCompleted;
        
        /// <remarks/>
        public event ConfermaCarrelloCompletedEventHandler ConfermaCarrelloCompleted;
        
        /// <remarks/>
        public event AggiornaOrdineCompletedEventHandler AggiornaOrdineCompleted;
        
        /// <remarks/>
        public event RegistraAnagintCompletedEventHandler RegistraAnagintCompleted;
        
        /// <remarks/>
        public event RiepilogoOrdineCompletedEventHandler RiepilogoOrdineCompleted;
        
        /// <remarks/>
        public event AvviaPagamentoOrdineCompletedEventHandler AvviaPagamentoOrdineCompleted;
        
        /// <remarks/>
        public event RicalcolaCarrelloCompletedEventHandler RicalcolaCarrelloCompleted;
        
        /// <remarks/>
        public event ElencoOrdiniCompletedEventHandler ElencoOrdiniCompleted;
        
        /// <remarks/>
        public event RecuperaEventiMailticketCompletedEventHandler RecuperaEventiMailticketCompleted;
        
        /// <remarks/>
        public event RecuperaBigliettiManEinetCompletedEventHandler RecuperaBigliettiManEinetCompleted;
        
        /// <remarks/>
        public event RecuperaBigliettiManMinetCompletedEventHandler RecuperaBigliettiManMinetCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://wsfiscale.mailticket.it/VerificaCodicePR", RequestNamespace="http://wsfiscale.mailticket.it/", ResponseNamespace="http://wsfiscale.mailticket.it/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RispPrevendita VerificaCodicePR(string CodePR, string IdMan, int IdEvento, int Tipologia, string CtSa) {
            object[] results = this.Invoke("VerificaCodicePR", new object[] {
                        CodePR,
                        IdMan,
                        IdEvento,
                        Tipologia,
                        CtSa});
            return ((RispPrevendita)(results[0]));
        }
        
        /// <remarks/>
        public void VerificaCodicePRAsync(string CodePR, string IdMan, int IdEvento, int Tipologia, string CtSa) {
            this.VerificaCodicePRAsync(CodePR, IdMan, IdEvento, Tipologia, CtSa, null);
        }
        
        /// <remarks/>
        public void VerificaCodicePRAsync(string CodePR, string IdMan, int IdEvento, int Tipologia, string CtSa, object userState) {
            if ((this.VerificaCodicePROperationCompleted == null)) {
                this.VerificaCodicePROperationCompleted = new System.Threading.SendOrPostCallback(this.OnVerificaCodicePROperationCompleted);
            }
            this.InvokeAsync("VerificaCodicePR", new object[] {
                        CodePR,
                        IdMan,
                        IdEvento,
                        Tipologia,
                        CtSa}, this.VerificaCodicePROperationCompleted, userState);
        }
        
        private void OnVerificaCodicePROperationCompleted(object arg) {
            if ((this.VerificaCodicePRCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VerificaCodicePRCompleted(this, new VerificaCodicePRCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://wsfiscale.mailticket.it/AggiungiAlCarrello", RequestNamespace="http://wsfiscale.mailticket.it/", ResponseNamespace="http://wsfiscale.mailticket.it/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RispAggCarrello AggiungiAlCarrello(string IdOrdine, string IdUtente, string TipoUtente, string id_man, string ctsa, string idEvMail, string codicePr, string CodiceCat, string idPosto, string BSID) {
            object[] results = this.Invoke("AggiungiAlCarrello", new object[] {
                        IdOrdine,
                        IdUtente,
                        TipoUtente,
                        id_man,
                        ctsa,
                        idEvMail,
                        codicePr,
                        CodiceCat,
                        idPosto,
                        BSID});
            return ((RispAggCarrello)(results[0]));
        }
        
        /// <remarks/>
        public void AggiungiAlCarrelloAsync(string IdOrdine, string IdUtente, string TipoUtente, string id_man, string ctsa, string idEvMail, string codicePr, string CodiceCat, string idPosto, string BSID) {
            this.AggiungiAlCarrelloAsync(IdOrdine, IdUtente, TipoUtente, id_man, ctsa, idEvMail, codicePr, CodiceCat, idPosto, BSID, null);
        }
        
        /// <remarks/>
        public void AggiungiAlCarrelloAsync(string IdOrdine, string IdUtente, string TipoUtente, string id_man, string ctsa, string idEvMail, string codicePr, string CodiceCat, string idPosto, string BSID, object userState) {
            if ((this.AggiungiAlCarrelloOperationCompleted == null)) {
                this.AggiungiAlCarrelloOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAggiungiAlCarrelloOperationCompleted);
            }
            this.InvokeAsync("AggiungiAlCarrello", new object[] {
                        IdOrdine,
                        IdUtente,
                        TipoUtente,
                        id_man,
                        ctsa,
                        idEvMail,
                        codicePr,
                        CodiceCat,
                        idPosto,
                        BSID}, this.AggiungiAlCarrelloOperationCompleted, userState);
        }
        
        private void OnAggiungiAlCarrelloOperationCompleted(object arg) {
            if ((this.AggiungiAlCarrelloCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AggiungiAlCarrelloCompleted(this, new AggiungiAlCarrelloCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://wsfiscale.mailticket.it/RimuoviDalCarrello", RequestNamespace="http://wsfiscale.mailticket.it/", ResponseNamespace="http://wsfiscale.mailticket.it/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RispPrevendita RimuoviDalCarrello(string IdUtente, string TipoUtente, string NumOrdine, string IdRiga) {
            object[] results = this.Invoke("RimuoviDalCarrello", new object[] {
                        IdUtente,
                        TipoUtente,
                        NumOrdine,
                        IdRiga});
            return ((RispPrevendita)(results[0]));
        }
        
        /// <remarks/>
        public void RimuoviDalCarrelloAsync(string IdUtente, string TipoUtente, string NumOrdine, string IdRiga) {
            this.RimuoviDalCarrelloAsync(IdUtente, TipoUtente, NumOrdine, IdRiga, null);
        }
        
        /// <remarks/>
        public void RimuoviDalCarrelloAsync(string IdUtente, string TipoUtente, string NumOrdine, string IdRiga, object userState) {
            if ((this.RimuoviDalCarrelloOperationCompleted == null)) {
                this.RimuoviDalCarrelloOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRimuoviDalCarrelloOperationCompleted);
            }
            this.InvokeAsync("RimuoviDalCarrello", new object[] {
                        IdUtente,
                        TipoUtente,
                        NumOrdine,
                        IdRiga}, this.RimuoviDalCarrelloOperationCompleted, userState);
        }
        
        private void OnRimuoviDalCarrelloOperationCompleted(object arg) {
            if ((this.RimuoviDalCarrelloCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RimuoviDalCarrelloCompleted(this, new RimuoviDalCarrelloCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://wsfiscale.mailticket.it/EliminaCarrello", RequestNamespace="http://wsfiscale.mailticket.it/", ResponseNamespace="http://wsfiscale.mailticket.it/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RispPrevendita EliminaCarrello(string IdUtente, string TipoUtente, string NumOrdine, System.DateTime DataAnnullamento) {
            object[] results = this.Invoke("EliminaCarrello", new object[] {
                        IdUtente,
                        TipoUtente,
                        NumOrdine,
                        DataAnnullamento});
            return ((RispPrevendita)(results[0]));
        }
        
        /// <remarks/>
        public void EliminaCarrelloAsync(string IdUtente, string TipoUtente, string NumOrdine, System.DateTime DataAnnullamento) {
            this.EliminaCarrelloAsync(IdUtente, TipoUtente, NumOrdine, DataAnnullamento, null);
        }
        
        /// <remarks/>
        public void EliminaCarrelloAsync(string IdUtente, string TipoUtente, string NumOrdine, System.DateTime DataAnnullamento, object userState) {
            if ((this.EliminaCarrelloOperationCompleted == null)) {
                this.EliminaCarrelloOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEliminaCarrelloOperationCompleted);
            }
            this.InvokeAsync("EliminaCarrello", new object[] {
                        IdUtente,
                        TipoUtente,
                        NumOrdine,
                        DataAnnullamento}, this.EliminaCarrelloOperationCompleted, userState);
        }
        
        private void OnEliminaCarrelloOperationCompleted(object arg) {
            if ((this.EliminaCarrelloCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EliminaCarrelloCompleted(this, new EliminaCarrelloCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://wsfiscale.mailticket.it/ConfermaCarrello", RequestNamespace="http://wsfiscale.mailticket.it/", ResponseNamespace="http://wsfiscale.mailticket.it/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RispPrevendita ConfermaCarrello(string IdUtente, string TipoUtente, string NumOrdine) {
            object[] results = this.Invoke("ConfermaCarrello", new object[] {
                        IdUtente,
                        TipoUtente,
                        NumOrdine});
            return ((RispPrevendita)(results[0]));
        }
        
        /// <remarks/>
        public void ConfermaCarrelloAsync(string IdUtente, string TipoUtente, string NumOrdine) {
            this.ConfermaCarrelloAsync(IdUtente, TipoUtente, NumOrdine, null);
        }
        
        /// <remarks/>
        public void ConfermaCarrelloAsync(string IdUtente, string TipoUtente, string NumOrdine, object userState) {
            if ((this.ConfermaCarrelloOperationCompleted == null)) {
                this.ConfermaCarrelloOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConfermaCarrelloOperationCompleted);
            }
            this.InvokeAsync("ConfermaCarrello", new object[] {
                        IdUtente,
                        TipoUtente,
                        NumOrdine}, this.ConfermaCarrelloOperationCompleted, userState);
        }
        
        private void OnConfermaCarrelloOperationCompleted(object arg) {
            if ((this.ConfermaCarrelloCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConfermaCarrelloCompleted(this, new ConfermaCarrelloCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://wsfiscale.mailticket.it/AggiornaOrdine", RequestNamespace="http://wsfiscale.mailticket.it/", ResponseNamespace="http://wsfiscale.mailticket.it/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RispPrevendita AggiornaOrdine(string IdUtente, string TipoUtente, string NumOrdine, string dsOrdine, string emailInvio, bool fatturazione, DatiFattOrdine datiFattura) {
            object[] results = this.Invoke("AggiornaOrdine", new object[] {
                        IdUtente,
                        TipoUtente,
                        NumOrdine,
                        dsOrdine,
                        emailInvio,
                        fatturazione,
                        datiFattura});
            return ((RispPrevendita)(results[0]));
        }
        
        /// <remarks/>
        public void AggiornaOrdineAsync(string IdUtente, string TipoUtente, string NumOrdine, string dsOrdine, string emailInvio, bool fatturazione, DatiFattOrdine datiFattura) {
            this.AggiornaOrdineAsync(IdUtente, TipoUtente, NumOrdine, dsOrdine, emailInvio, fatturazione, datiFattura, null);
        }
        
        /// <remarks/>
        public void AggiornaOrdineAsync(string IdUtente, string TipoUtente, string NumOrdine, string dsOrdine, string emailInvio, bool fatturazione, DatiFattOrdine datiFattura, object userState) {
            if ((this.AggiornaOrdineOperationCompleted == null)) {
                this.AggiornaOrdineOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAggiornaOrdineOperationCompleted);
            }
            this.InvokeAsync("AggiornaOrdine", new object[] {
                        IdUtente,
                        TipoUtente,
                        NumOrdine,
                        dsOrdine,
                        emailInvio,
                        fatturazione,
                        datiFattura}, this.AggiornaOrdineOperationCompleted, userState);
        }
        
        private void OnAggiornaOrdineOperationCompleted(object arg) {
            if ((this.AggiornaOrdineCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AggiornaOrdineCompleted(this, new AggiornaOrdineCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://wsfiscale.mailticket.it/RegistraAnagint", RequestNamespace="http://wsfiscale.mailticket.it/", ResponseNamespace="http://wsfiscale.mailticket.it/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RispPrevendita RegistraAnagint(string IdUtente, string TipoUtente, string NumOrdine, string IdRiga, string Cognome, string Nome, bool Privacy, string IdSuppDig) {
            object[] results = this.Invoke("RegistraAnagint", new object[] {
                        IdUtente,
                        TipoUtente,
                        NumOrdine,
                        IdRiga,
                        Cognome,
                        Nome,
                        Privacy,
                        IdSuppDig});
            return ((RispPrevendita)(results[0]));
        }
        
        /// <remarks/>
        public void RegistraAnagintAsync(string IdUtente, string TipoUtente, string NumOrdine, string IdRiga, string Cognome, string Nome, bool Privacy, string IdSuppDig) {
            this.RegistraAnagintAsync(IdUtente, TipoUtente, NumOrdine, IdRiga, Cognome, Nome, Privacy, IdSuppDig, null);
        }
        
        /// <remarks/>
        public void RegistraAnagintAsync(string IdUtente, string TipoUtente, string NumOrdine, string IdRiga, string Cognome, string Nome, bool Privacy, string IdSuppDig, object userState) {
            if ((this.RegistraAnagintOperationCompleted == null)) {
                this.RegistraAnagintOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRegistraAnagintOperationCompleted);
            }
            this.InvokeAsync("RegistraAnagint", new object[] {
                        IdUtente,
                        TipoUtente,
                        NumOrdine,
                        IdRiga,
                        Cognome,
                        Nome,
                        Privacy,
                        IdSuppDig}, this.RegistraAnagintOperationCompleted, userState);
        }
        
        private void OnRegistraAnagintOperationCompleted(object arg) {
            if ((this.RegistraAnagintCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RegistraAnagintCompleted(this, new RegistraAnagintCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://wsfiscale.mailticket.it/RiepilogoOrdine", RequestNamespace="http://wsfiscale.mailticket.it/", ResponseNamespace="http://wsfiscale.mailticket.it/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RispostaRiepilogo RiepilogoOrdine(string IdUtente, string TipoUtente, string NumOrdine) {
            object[] results = this.Invoke("RiepilogoOrdine", new object[] {
                        IdUtente,
                        TipoUtente,
                        NumOrdine});
            return ((RispostaRiepilogo)(results[0]));
        }
        
        /// <remarks/>
        public void RiepilogoOrdineAsync(string IdUtente, string TipoUtente, string NumOrdine) {
            this.RiepilogoOrdineAsync(IdUtente, TipoUtente, NumOrdine, null);
        }
        
        /// <remarks/>
        public void RiepilogoOrdineAsync(string IdUtente, string TipoUtente, string NumOrdine, object userState) {
            if ((this.RiepilogoOrdineOperationCompleted == null)) {
                this.RiepilogoOrdineOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRiepilogoOrdineOperationCompleted);
            }
            this.InvokeAsync("RiepilogoOrdine", new object[] {
                        IdUtente,
                        TipoUtente,
                        NumOrdine}, this.RiepilogoOrdineOperationCompleted, userState);
        }
        
        private void OnRiepilogoOrdineOperationCompleted(object arg) {
            if ((this.RiepilogoOrdineCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RiepilogoOrdineCompleted(this, new RiepilogoOrdineCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://wsfiscale.mailticket.it/AvviaPagamentoOrdine", RequestNamespace="http://wsfiscale.mailticket.it/", ResponseNamespace="http://wsfiscale.mailticket.it/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RispostaAvviaPag AvviaPagamentoOrdine(string IdUtente, string TipoUtente, string emailUtente, string NumOrdine) {
            object[] results = this.Invoke("AvviaPagamentoOrdine", new object[] {
                        IdUtente,
                        TipoUtente,
                        emailUtente,
                        NumOrdine});
            return ((RispostaAvviaPag)(results[0]));
        }
        
        /// <remarks/>
        public void AvviaPagamentoOrdineAsync(string IdUtente, string TipoUtente, string emailUtente, string NumOrdine) {
            this.AvviaPagamentoOrdineAsync(IdUtente, TipoUtente, emailUtente, NumOrdine, null);
        }
        
        /// <remarks/>
        public void AvviaPagamentoOrdineAsync(string IdUtente, string TipoUtente, string emailUtente, string NumOrdine, object userState) {
            if ((this.AvviaPagamentoOrdineOperationCompleted == null)) {
                this.AvviaPagamentoOrdineOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAvviaPagamentoOrdineOperationCompleted);
            }
            this.InvokeAsync("AvviaPagamentoOrdine", new object[] {
                        IdUtente,
                        TipoUtente,
                        emailUtente,
                        NumOrdine}, this.AvviaPagamentoOrdineOperationCompleted, userState);
        }
        
        private void OnAvviaPagamentoOrdineOperationCompleted(object arg) {
            if ((this.AvviaPagamentoOrdineCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AvviaPagamentoOrdineCompleted(this, new AvviaPagamentoOrdineCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://wsfiscale.mailticket.it/RicalcolaCarrello", RequestNamespace="http://wsfiscale.mailticket.it/", ResponseNamespace="http://wsfiscale.mailticket.it/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RispPrevendita RicalcolaCarrello(string IdUtente, string TipoUtente, string NumOrdine) {
            object[] results = this.Invoke("RicalcolaCarrello", new object[] {
                        IdUtente,
                        TipoUtente,
                        NumOrdine});
            return ((RispPrevendita)(results[0]));
        }
        
        /// <remarks/>
        public void RicalcolaCarrelloAsync(string IdUtente, string TipoUtente, string NumOrdine) {
            this.RicalcolaCarrelloAsync(IdUtente, TipoUtente, NumOrdine, null);
        }
        
        /// <remarks/>
        public void RicalcolaCarrelloAsync(string IdUtente, string TipoUtente, string NumOrdine, object userState) {
            if ((this.RicalcolaCarrelloOperationCompleted == null)) {
                this.RicalcolaCarrelloOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRicalcolaCarrelloOperationCompleted);
            }
            this.InvokeAsync("RicalcolaCarrello", new object[] {
                        IdUtente,
                        TipoUtente,
                        NumOrdine}, this.RicalcolaCarrelloOperationCompleted, userState);
        }
        
        private void OnRicalcolaCarrelloOperationCompleted(object arg) {
            if ((this.RicalcolaCarrelloCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RicalcolaCarrelloCompleted(this, new RicalcolaCarrelloCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://wsfiscale.mailticket.it/ElencoOrdini", RequestNamespace="http://wsfiscale.mailticket.it/", ResponseNamespace="http://wsfiscale.mailticket.it/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RispPrevendita ElencoOrdini(string IdUtente, string TipoUtente) {
            object[] results = this.Invoke("ElencoOrdini", new object[] {
                        IdUtente,
                        TipoUtente});
            return ((RispPrevendita)(results[0]));
        }
        
        /// <remarks/>
        public void ElencoOrdiniAsync(string IdUtente, string TipoUtente) {
            this.ElencoOrdiniAsync(IdUtente, TipoUtente, null);
        }
        
        /// <remarks/>
        public void ElencoOrdiniAsync(string IdUtente, string TipoUtente, object userState) {
            if ((this.ElencoOrdiniOperationCompleted == null)) {
                this.ElencoOrdiniOperationCompleted = new System.Threading.SendOrPostCallback(this.OnElencoOrdiniOperationCompleted);
            }
            this.InvokeAsync("ElencoOrdini", new object[] {
                        IdUtente,
                        TipoUtente}, this.ElencoOrdiniOperationCompleted, userState);
        }
        
        private void OnElencoOrdiniOperationCompleted(object arg) {
            if ((this.ElencoOrdiniCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ElencoOrdiniCompleted(this, new ElencoOrdiniCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://wsfiscale.mailticket.it/RecuperaEventiMailticket", RequestNamespace="http://wsfiscale.mailticket.it/", ResponseNamespace="http://wsfiscale.mailticket.it/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public EventoMail[] RecuperaEventiMailticket() {
            object[] results = this.Invoke("RecuperaEventiMailticket", new object[0]);
            return ((EventoMail[])(results[0]));
        }
        
        /// <remarks/>
        public void RecuperaEventiMailticketAsync() {
            this.RecuperaEventiMailticketAsync(null);
        }
        
        /// <remarks/>
        public void RecuperaEventiMailticketAsync(object userState) {
            if ((this.RecuperaEventiMailticketOperationCompleted == null)) {
                this.RecuperaEventiMailticketOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRecuperaEventiMailticketOperationCompleted);
            }
            this.InvokeAsync("RecuperaEventiMailticket", new object[0], this.RecuperaEventiMailticketOperationCompleted, userState);
        }
        
        private void OnRecuperaEventiMailticketOperationCompleted(object arg) {
            if ((this.RecuperaEventiMailticketCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RecuperaEventiMailticketCompleted(this, new RecuperaEventiMailticketCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://wsfiscale.mailticket.it/RecuperaBigliettiManEinet", RequestNamespace="http://wsfiscale.mailticket.it/", ResponseNamespace="http://wsfiscale.mailticket.it/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Titoli[] RecuperaBigliettiManEinet(string DscMan, string OrdinePosto) {
            object[] results = this.Invoke("RecuperaBigliettiManEinet", new object[] {
                        DscMan,
                        OrdinePosto});
            return ((Titoli[])(results[0]));
        }
        
        /// <remarks/>
        public void RecuperaBigliettiManEinetAsync(string DscMan, string OrdinePosto) {
            this.RecuperaBigliettiManEinetAsync(DscMan, OrdinePosto, null);
        }
        
        /// <remarks/>
        public void RecuperaBigliettiManEinetAsync(string DscMan, string OrdinePosto, object userState) {
            if ((this.RecuperaBigliettiManEinetOperationCompleted == null)) {
                this.RecuperaBigliettiManEinetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRecuperaBigliettiManEinetOperationCompleted);
            }
            this.InvokeAsync("RecuperaBigliettiManEinet", new object[] {
                        DscMan,
                        OrdinePosto}, this.RecuperaBigliettiManEinetOperationCompleted, userState);
        }
        
        private void OnRecuperaBigliettiManEinetOperationCompleted(object arg) {
            if ((this.RecuperaBigliettiManEinetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RecuperaBigliettiManEinetCompleted(this, new RecuperaBigliettiManEinetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://wsfiscale.mailticket.it/RecuperaBigliettiManMinet", RequestNamespace="http://wsfiscale.mailticket.it/", ResponseNamespace="http://wsfiscale.mailticket.it/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Titoli[] RecuperaBigliettiManMinet(string DscMan) {
            object[] results = this.Invoke("RecuperaBigliettiManMinet", new object[] {
                        DscMan});
            return ((Titoli[])(results[0]));
        }
        
        /// <remarks/>
        public void RecuperaBigliettiManMinetAsync(string DscMan) {
            this.RecuperaBigliettiManMinetAsync(DscMan, null);
        }
        
        /// <remarks/>
        public void RecuperaBigliettiManMinetAsync(string DscMan, object userState) {
            if ((this.RecuperaBigliettiManMinetOperationCompleted == null)) {
                this.RecuperaBigliettiManMinetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRecuperaBigliettiManMinetOperationCompleted);
            }
            this.InvokeAsync("RecuperaBigliettiManMinet", new object[] {
                        DscMan}, this.RecuperaBigliettiManMinetOperationCompleted, userState);
        }
        
        private void OnRecuperaBigliettiManMinetOperationCompleted(object arg) {
            if ((this.RecuperaBigliettiManMinetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RecuperaBigliettiManMinetCompleted(this, new RecuperaBigliettiManMinetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsfiscale.mailticket.it/")]
    public partial class RispPrevendita {
        
        private bool esitoField;
        
        private string messaggioField;
        
        /// <remarks/>
        public bool Esito {
            get {
                return this.esitoField;
            }
            set {
                this.esitoField = value;
            }
        }
        
        /// <remarks/>
        public string Messaggio {
            get {
                return this.messaggioField;
            }
            set {
                this.messaggioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsfiscale.mailticket.it/")]
    public partial class Titoli {
        
        private string idTitoloField;
        
        private string bigliettoAbbonamentoField;
        
        private string ordine_postoField;
        
        private string descrizioneField;
        
        private decimal prezzoTitoloField;
        
        private int tipologiaBigliettoField;
        
        private bool ivaPreassoltaField;
        
        private bool servizioField;
        
        private int progressivoField;
        
        private decimal prevenditaField;
        
        /// <remarks/>
        public string IdTitolo {
            get {
                return this.idTitoloField;
            }
            set {
                this.idTitoloField = value;
            }
        }
        
        /// <remarks/>
        public string BigliettoAbbonamento {
            get {
                return this.bigliettoAbbonamentoField;
            }
            set {
                this.bigliettoAbbonamentoField = value;
            }
        }
        
        /// <remarks/>
        public string ordine_posto {
            get {
                return this.ordine_postoField;
            }
            set {
                this.ordine_postoField = value;
            }
        }
        
        /// <remarks/>
        public string Descrizione {
            get {
                return this.descrizioneField;
            }
            set {
                this.descrizioneField = value;
            }
        }
        
        /// <remarks/>
        public decimal PrezzoTitolo {
            get {
                return this.prezzoTitoloField;
            }
            set {
                this.prezzoTitoloField = value;
            }
        }
        
        /// <remarks/>
        public int TipologiaBiglietto {
            get {
                return this.tipologiaBigliettoField;
            }
            set {
                this.tipologiaBigliettoField = value;
            }
        }
        
        /// <remarks/>
        public bool IvaPreassolta {
            get {
                return this.ivaPreassoltaField;
            }
            set {
                this.ivaPreassoltaField = value;
            }
        }
        
        /// <remarks/>
        public bool Servizio {
            get {
                return this.servizioField;
            }
            set {
                this.servizioField = value;
            }
        }
        
        /// <remarks/>
        public int Progressivo {
            get {
                return this.progressivoField;
            }
            set {
                this.progressivoField = value;
            }
        }
        
        /// <remarks/>
        public decimal Prevendita {
            get {
                return this.prevenditaField;
            }
            set {
                this.prevenditaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsfiscale.mailticket.it/")]
    public partial class EventoMail {
        
        private string idSpettacoloField;
        
        private string idSpettMailField;
        
        private string idEventoField;
        
        private string idManField;
        
        private string descEventoField;
        
        private System.DateTime dataeventoField;
        
        private string tipoField;
        
        private string linkImmagineField;
        
        private string spettacoloField;
        
        private string locationField;
        
        /// <remarks/>
        public string idSpettacolo {
            get {
                return this.idSpettacoloField;
            }
            set {
                this.idSpettacoloField = value;
            }
        }
        
        /// <remarks/>
        public string idSpettMail {
            get {
                return this.idSpettMailField;
            }
            set {
                this.idSpettMailField = value;
            }
        }
        
        /// <remarks/>
        public string idEvento {
            get {
                return this.idEventoField;
            }
            set {
                this.idEventoField = value;
            }
        }
        
        /// <remarks/>
        public string idMan {
            get {
                return this.idManField;
            }
            set {
                this.idManField = value;
            }
        }
        
        /// <remarks/>
        public string DescEvento {
            get {
                return this.descEventoField;
            }
            set {
                this.descEventoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Dataevento {
            get {
                return this.dataeventoField;
            }
            set {
                this.dataeventoField = value;
            }
        }
        
        /// <remarks/>
        public string Tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
            }
        }
        
        /// <remarks/>
        public string LinkImmagine {
            get {
                return this.linkImmagineField;
            }
            set {
                this.linkImmagineField = value;
            }
        }
        
        /// <remarks/>
        public string Spettacolo {
            get {
                return this.spettacoloField;
            }
            set {
                this.spettacoloField = value;
            }
        }
        
        /// <remarks/>
        public string Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }

        public static implicit operator DataTable(EventoMail v)
        {
            throw new NotImplementedException();
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsfiscale.mailticket.it/")]
    public partial class RispostaAvviaPag {
        
        private bool esitoField;
        
        private string messaggioField;
        
        private bool evasioneFattaField;
        
        private bool goPagamentoField;
        
        private bool goCalcCarrelloField;
        
        /// <remarks/>
        public bool Esito {
            get {
                return this.esitoField;
            }
            set {
                this.esitoField = value;
            }
        }
        
        /// <remarks/>
        public string Messaggio {
            get {
                return this.messaggioField;
            }
            set {
                this.messaggioField = value;
            }
        }
        
        /// <remarks/>
        public bool evasioneFatta {
            get {
                return this.evasioneFattaField;
            }
            set {
                this.evasioneFattaField = value;
            }
        }
        
        /// <remarks/>
        public bool GoPagamento {
            get {
                return this.goPagamentoField;
            }
            set {
                this.goPagamentoField = value;
            }
        }
        
        /// <remarks/>
        public bool GoCalcCarrello {
            get {
                return this.goCalcCarrelloField;
            }
            set {
                this.goCalcCarrelloField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsfiscale.mailticket.it/")]
    public partial class ArticoliCarrello {
        
        private string idManCtSaField;
        
        private string idRowField;
        
        private bool rigaStornataField;
        
        private string descrTipoField;
        
        private string descrizioneField;
        
        private string descrValField;
        
        private decimal corrispettivoField;
        
        private string pathPDFField;
        
        private string codeunicoField;
        
        /// <remarks/>
        public string IdManCtSa {
            get {
                return this.idManCtSaField;
            }
            set {
                this.idManCtSaField = value;
            }
        }
        
        /// <remarks/>
        public string IdRow {
            get {
                return this.idRowField;
            }
            set {
                this.idRowField = value;
            }
        }
        
        /// <remarks/>
        public bool RigaStornata {
            get {
                return this.rigaStornataField;
            }
            set {
                this.rigaStornataField = value;
            }
        }
        
        /// <remarks/>
        public string DescrTipo {
            get {
                return this.descrTipoField;
            }
            set {
                this.descrTipoField = value;
            }
        }
        
        /// <remarks/>
        public string Descrizione {
            get {
                return this.descrizioneField;
            }
            set {
                this.descrizioneField = value;
            }
        }
        
        /// <remarks/>
        public string DescrVal {
            get {
                return this.descrValField;
            }
            set {
                this.descrValField = value;
            }
        }
        
        /// <remarks/>
        public decimal Corrispettivo {
            get {
                return this.corrispettivoField;
            }
            set {
                this.corrispettivoField = value;
            }
        }
        
        /// <remarks/>
        public string PathPDF {
            get {
                return this.pathPDFField;
            }
            set {
                this.pathPDFField = value;
            }
        }
        
        /// <remarks/>
        public string Codeunico {
            get {
                return this.codeunicoField;
            }
            set {
                this.codeunicoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsfiscale.mailticket.it/")]
    public partial class RispostaRiepilogo {
        
        private bool esitoField;
        
        private string messaggioField;
        
        private bool ordineChiusoField;
        
        private bool ordinePagatoField;
        
        private bool ordineEvasoField;
        
        private bool ordineInvioEmailField;
        
        private decimal totaleNettoField;
        
        private decimal totaleCommisioniField;
        
        private decimal totaleOrdineField;
        
        private bool ordineDatiFattField;
        
        private string messStatoOrdineField;
        
        private string urlCodiceUnicoField;
        
        private ArticoliCarrello[] elencoArtField;
        
        /// <remarks/>
        public bool Esito {
            get {
                return this.esitoField;
            }
            set {
                this.esitoField = value;
            }
        }
        
        /// <remarks/>
        public string Messaggio {
            get {
                return this.messaggioField;
            }
            set {
                this.messaggioField = value;
            }
        }
        
        /// <remarks/>
        public bool OrdineChiuso {
            get {
                return this.ordineChiusoField;
            }
            set {
                this.ordineChiusoField = value;
            }
        }
        
        /// <remarks/>
        public bool OrdinePagato {
            get {
                return this.ordinePagatoField;
            }
            set {
                this.ordinePagatoField = value;
            }
        }
        
        /// <remarks/>
        public bool OrdineEvaso {
            get {
                return this.ordineEvasoField;
            }
            set {
                this.ordineEvasoField = value;
            }
        }
        
        /// <remarks/>
        public bool OrdineInvioEmail {
            get {
                return this.ordineInvioEmailField;
            }
            set {
                this.ordineInvioEmailField = value;
            }
        }
        
        /// <remarks/>
        public decimal TotaleNetto {
            get {
                return this.totaleNettoField;
            }
            set {
                this.totaleNettoField = value;
            }
        }
        
        /// <remarks/>
        public decimal TotaleCommisioni {
            get {
                return this.totaleCommisioniField;
            }
            set {
                this.totaleCommisioniField = value;
            }
        }
        
        /// <remarks/>
        public decimal TotaleOrdine {
            get {
                return this.totaleOrdineField;
            }
            set {
                this.totaleOrdineField = value;
            }
        }
        
        /// <remarks/>
        public bool OrdineDatiFatt {
            get {
                return this.ordineDatiFattField;
            }
            set {
                this.ordineDatiFattField = value;
            }
        }
        
        /// <remarks/>
        public string MessStatoOrdine {
            get {
                return this.messStatoOrdineField;
            }
            set {
                this.messStatoOrdineField = value;
            }
        }
        
        /// <remarks/>
        public string UrlCodiceUnico {
            get {
                return this.urlCodiceUnicoField;
            }
            set {
                this.urlCodiceUnicoField = value;
            }
        }
        
        /// <remarks/>
        public ArticoliCarrello[] ElencoArt {
            get {
                return this.elencoArtField;
            }
            set {
                this.elencoArtField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsfiscale.mailticket.it/")]
    public partial class DatiFattOrdine {
        
        private string italiaEsteroField;
        
        private bool aziendaField;
        
        private string ragioneSocialeField;
        
        private string congomeField;
        
        private string nomeField;
        
        private string pICFField;
        
        private string indirizzoField;
        
        private string cAPField;
        
        private string localitaField;
        
        private string provinciaField;
        
        private string emailField;
        
        /// <remarks/>
        public string ItaliaEstero {
            get {
                return this.italiaEsteroField;
            }
            set {
                this.italiaEsteroField = value;
            }
        }
        
        /// <remarks/>
        public bool Azienda {
            get {
                return this.aziendaField;
            }
            set {
                this.aziendaField = value;
            }
        }
        
        /// <remarks/>
        public string RagioneSociale {
            get {
                return this.ragioneSocialeField;
            }
            set {
                this.ragioneSocialeField = value;
            }
        }
        
        /// <remarks/>
        public string Congome {
            get {
                return this.congomeField;
            }
            set {
                this.congomeField = value;
            }
        }
        
        /// <remarks/>
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        public string PICF {
            get {
                return this.pICFField;
            }
            set {
                this.pICFField = value;
            }
        }
        
        /// <remarks/>
        public string Indirizzo {
            get {
                return this.indirizzoField;
            }
            set {
                this.indirizzoField = value;
            }
        }
        
        /// <remarks/>
        public string CAP {
            get {
                return this.cAPField;
            }
            set {
                this.cAPField = value;
            }
        }
        
        /// <remarks/>
        public string Localita {
            get {
                return this.localitaField;
            }
            set {
                this.localitaField = value;
            }
        }
        
        /// <remarks/>
        public string Provincia {
            get {
                return this.provinciaField;
            }
            set {
                this.provinciaField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsfiscale.mailticket.it/")]
    public partial class RispAggCarrello {
        
        private bool esitoField;
        
        private string messaggioField;
        
        private string numeroOrdineField;
        
        private decimal totaleNettoField;
        
        private decimal totaleCommissioniField;
        
        private decimal totaleOrdineField;
        
        private decimal totalePrezzoOrdineField;
        
        private decimal totalePrevenditaField;
        
        private int numeroRigaField;
        
        /// <remarks/>
        public bool Esito {
            get {
                return this.esitoField;
            }
            set {
                this.esitoField = value;
            }
        }
        
        /// <remarks/>
        public string Messaggio {
            get {
                return this.messaggioField;
            }
            set {
                this.messaggioField = value;
            }
        }
        
        /// <remarks/>
        public string NumeroOrdine {
            get {
                return this.numeroOrdineField;
            }
            set {
                this.numeroOrdineField = value;
            }
        }
        
        /// <remarks/>
        public decimal TotaleNetto {
            get {
                return this.totaleNettoField;
            }
            set {
                this.totaleNettoField = value;
            }
        }
        
        /// <remarks/>
        public decimal TotaleCommissioni {
            get {
                return this.totaleCommissioniField;
            }
            set {
                this.totaleCommissioniField = value;
            }
        }
        
        /// <remarks/>
        public decimal TotaleOrdine {
            get {
                return this.totaleOrdineField;
            }
            set {
                this.totaleOrdineField = value;
            }
        }
        
        /// <remarks/>
        public decimal TotalePrezzoOrdine {
            get {
                return this.totalePrezzoOrdineField;
            }
            set {
                this.totalePrezzoOrdineField = value;
            }
        }
        
        /// <remarks/>
        public decimal TotalePrevendita {
            get {
                return this.totalePrevenditaField;
            }
            set {
                this.totalePrevenditaField = value;
            }
        }
        
        /// <remarks/>
        public int NumeroRiga {
            get {
                return this.numeroRigaField;
            }
            set {
                this.numeroRigaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void VerificaCodicePRCompletedEventHandler(object sender, VerificaCodicePRCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VerificaCodicePRCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VerificaCodicePRCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RispPrevendita Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RispPrevendita)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void AggiungiAlCarrelloCompletedEventHandler(object sender, AggiungiAlCarrelloCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AggiungiAlCarrelloCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AggiungiAlCarrelloCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RispAggCarrello Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RispAggCarrello)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void RimuoviDalCarrelloCompletedEventHandler(object sender, RimuoviDalCarrelloCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RimuoviDalCarrelloCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RimuoviDalCarrelloCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RispPrevendita Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RispPrevendita)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void EliminaCarrelloCompletedEventHandler(object sender, EliminaCarrelloCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EliminaCarrelloCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EliminaCarrelloCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RispPrevendita Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RispPrevendita)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void ConfermaCarrelloCompletedEventHandler(object sender, ConfermaCarrelloCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConfermaCarrelloCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConfermaCarrelloCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RispPrevendita Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RispPrevendita)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void AggiornaOrdineCompletedEventHandler(object sender, AggiornaOrdineCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AggiornaOrdineCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AggiornaOrdineCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RispPrevendita Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RispPrevendita)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void RegistraAnagintCompletedEventHandler(object sender, RegistraAnagintCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RegistraAnagintCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RegistraAnagintCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RispPrevendita Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RispPrevendita)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void RiepilogoOrdineCompletedEventHandler(object sender, RiepilogoOrdineCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RiepilogoOrdineCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RiepilogoOrdineCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RispostaRiepilogo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RispostaRiepilogo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void AvviaPagamentoOrdineCompletedEventHandler(object sender, AvviaPagamentoOrdineCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AvviaPagamentoOrdineCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AvviaPagamentoOrdineCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RispostaAvviaPag Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RispostaAvviaPag)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void RicalcolaCarrelloCompletedEventHandler(object sender, RicalcolaCarrelloCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RicalcolaCarrelloCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RicalcolaCarrelloCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RispPrevendita Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RispPrevendita)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void ElencoOrdiniCompletedEventHandler(object sender, ElencoOrdiniCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ElencoOrdiniCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ElencoOrdiniCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RispPrevendita Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RispPrevendita)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void RecuperaEventiMailticketCompletedEventHandler(object sender, RecuperaEventiMailticketCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RecuperaEventiMailticketCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RecuperaEventiMailticketCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public EventoMail[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((EventoMail[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void RecuperaBigliettiManEinetCompletedEventHandler(object sender, RecuperaBigliettiManEinetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RecuperaBigliettiManEinetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RecuperaBigliettiManEinetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Titoli[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Titoli[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void RecuperaBigliettiManMinetCompletedEventHandler(object sender, RecuperaBigliettiManMinetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RecuperaBigliettiManMinetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RecuperaBigliettiManMinetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Titoli[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Titoli[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591